WebShop/WebShop/ViewModels/ErrorViewModel.cs
namespace WebShop.UILayer.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebShop/WebShop/ViewModels/ProductViewModel.cs
namespace WebShop.UILayer.ViewModels
{
    public class ProductViewModel
    {
        public int Id { get; set; }

        public decimal Price { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public string Category { get; set; }

        public int Amount { get; set; }
    }
}

WebShop/WebShop/ViewModels/UserLoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebShop.UILayer.ViewModels
{
    public class UserLoginViewModel
    {
        [Required]
        public string Login { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

WebShop/WebShop/ViewModels/UserRegisterViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace WebShop.UILayer.ViewModels
{
    public class UserRegisterViewModel
    {
        [Required]
        [MinLength(4)]
        [MaxLength(20)]
        public string Login { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare("ConfirmPassword")]
        [MinLength(6)]
        [MaxLength(33)]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
    }
}

WebShop/WebShop/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using WebShop.BusinessLayer;
using WebShop.BusinessLayer.Interfaces;
using WebShop.UILayer.ViewModels;

namespace WebShop.UILayer.Controllers
{
    public class AccountController : Controller
    {
        private readonly IUserService userSerivce;

        private readonly UserValidator validator;

        public AccountController(IUserService serivce, UserValidator validator)
        {
            this.validator = validator;
            userSerivce = serivce;
        }
        
        // GET: AccountController
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Login(UserLoginViewModel model)
        {
            if (!validator.CheckUserInfo(model.Login, model.Password))
            {
                ModelState.AddModelError("Login", "Неправильный логин или пароль");
                return View(model);
            }

            var user = userSerivce.LogIn(model.Login);

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Role, user.Role.ToString()),
                new Claim(type: "Id", value: user.Id.ToString()),
                new Claim(ClaimTypes.Name, user.Login),
            };

            var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimIdentity));

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Register()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult Register(UserRegisterViewModel model)
        {
            if (!validator.LoginValidate(model.Login))
            {
                ModelState.AddModelError("Login", "Имя пользователя занято");
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            userSerivce.RegisterUser(model.Login, model.Password);

            return RedirectToAction("Index", "Home");
        }

        public async Task<ActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Index", "Home");
        }
    }
}

WebShop/WebShop/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using WebShop.BusinessLayer.Interfaces;

namespace WebShop.UILayer.Controllers
{
    public class CatalogController : Controller
    {
        private readonly IProductService productService;

        public CatalogController(IProductService service)
        {
            productService = service;
        }

        public IActionResult Index()
        {
            return View(productService.GetCatalog());
        }
    }
}

WebShop/WebShop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace WebShop.UILayer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

WebShop/WebShop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using WebShop.BusinessLayer.Interfaces;

namespace WebShop.UILayer.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService productService;

        public ProductController(IProductService service)
        {
            productService = service;
        }

        public IActionResult Index(int id)
        {
            return View(productService.GetProduct(id));
        }
    }
}

WebShop/WebShop/Views/Catalog/Index.cshtml
@model IEnumerable<WebShop.Shared.Models.Product>

<!DOCTYPE html>

<html>
<head>
    <title>Каталог товаров</title>
</head>
<body>
    <h3>Товары</h3>
    <table class="table">
        @foreach (var item in Model)
        {
        <tr><td>@item.Title</td><td>@item.Price</td><td>@item.Category</td><td><a href="~/Product?id=@item.Id">Подробнее</a></td></tr>
        }
    </table>
</body>
</html>

WebShop/WebShop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebShop/WebShop/Views/Product/Index.cshtml
@model WebShop.Shared.Models.Product

WebShop/WebShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Index">Каталог</a>
                        </li>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Вход</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Личный кабинет</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Выход</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>